stage:
  - lab_01
  - lab_02

lab_01:
  stage: lab_01

  script:
  - apk add --no-cache gcc musl-dev
  - cd lab_01
  - g++ main.cpp

  tags:
  - compile

lab_02:
  stage: lab_02

  script:
  - apk add --no-cache gcc musl-dev
  - cd lab_02
  - g++ main.cpp

  tags: compile
  
