image: alpine:3.7

stages:
  - lab_01
  - lab_02
  - lab_03
  - lab_04
  - lab_05
  - lab_06
  - lab_07
  - cppcheck
  - cloc

lab_01:
  stage: lab_01

  script:
  - apk add --no-cache g++
  - cd lab_01
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

lab_02:
  stage: lab_02

  script:
  - apk add --no-cache g++
  - cd lab_02
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

lab_03:
  stage: lab_03

  script:
  - apk add --no-cache g++
  - cd lab_03
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

lab_04:
  stage: lab_04

  script:
  - apk add --no-cache g++
  - cd lab_04
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

lab_05:
  stage: lab_05

  script:
  - apk add --no-cache g++
  - cd lab_05
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

lab_02:
  stage: lab_06

  script:
  - apk add --no-cache g++
  - cd lab_06
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

lab_07:
  stage: lab_07

  script:
  - apk add --no-cache g++
  - cd lab_07
  - g++ -std=c++14 -Wall -Werror main.cpp
  - cd

  only:
  - master
  - cppcheck-fix

cppcheck:
  stage: cppcheck

  script:
  - apk add --no-cache cppcheck
  - cppcheck --enable=all --inconclusive --error-exitcode=1 .

cloc:
  stage: cloc

  script:
  - apk add --no-cache cloc
  - cloc .

  only:
  - master

