image: alpine:3.7

stages:
  - lab_01
  - lab_02

lab_01:
  stage: lab_01

  script:
  - apk add --no-cache g++ 
  - cd lab_01
  - g++ main.cpp
  - cd

  only:
  - master
    
lab_02:
  stage: lab_02

  script:
  - apk add --no-cache g++
  - cd lab_02
  - g++ main.cpp
  - cd

  only:
  - master
